### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by F-Ruxton** [F-Ruxton/taskata#11]
Deploying application
/home/travis/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:1515:in `stat': No such file or directory - ./build/. (Errno::ENOENT)

From the travis build. I set it to use /build as the deploy source. Perhaps add a cleanup task to remove it after deploy?

**Comment by robhowell** [comment]
I thought that would work, weird. Yep, probably best just do the cleanup after instead.

I read something about being able to set some kind of "no cleanup" or "no delete" option in Travis, so that might be another option we could try?

Thanks,
Rob

**Comment by F-Ruxton** [comment]
Using Travis's deploy option for pages requires skip_cleanup: true. I've tried using the deploy: run: and the after_script hooks to execute a rm -rf ./build but haven't got it to work either way. I guess because the push to master happens first it's too late for a simple rm. 

The reason for needing build in the repo is to use as the source to push to gh-pages, otherwise travis pushes the whole project over. So I’m going to look more closely at the deploy.sh script you linked originally. The process seems to be build locally -> copy build to separate repo -> push that to gh-pages, so build could be gitignored again. It’s quite complicated - to me anyway :) - so taking a while to make sense of it all.

Also CNAME isn't a dotfile, so confused why the --dotfile flag was needed.

**Comment by F-Ruxton** [comment]
I'm not getting very far with this at the moment. As long as the push starts without a /build present the build still fails with or without build in gitignore. Haven't fixed anything

**Comment by F-Ruxton** [comment]
Fixed build I think, however site currently not live at either taskata.js.org or f-ruxton.github.io/taskata/.
