### ISSUE TITLE
Research and decide on hosting/domain options

### ISSUE THREAD

**Issue by robhowell** [F-Ruxton/taskata#3]

**Comment by robhowell** [comment]
@F-Ruxton If we keep this as a purely client-side app then it means we can host it anywhere that supports basic static website hosting.

I started looking at hosting it on Amazon S3 and using a subdomain of one of my domains, which would have a cost of somewhere between free and extremely cheap, but I just found another option that is even easier: hosting it on GitHub Pages and using a free subdomain from https://dns.js.org/

From what I remember of using it previously, GitHub Pages allows people to host webpages for their projects using either a directory within the master branch or using a special branch named gh-pages. If we use the latter option then we can still use a proper build tool like Travis for running tests etc, but once tests complete successfully on the master branch then I think we should be able to create a publish step that will push the built site to the gh-pages branch.

**Comment by robhowell** [comment]
@F-Ruxton

WINNING! 👍  I was just reading a page that explains how to deploy to GitHub Pages using some SSH script - https://gist.github.com/domenic/ec8b0fc8ab45f39403dd - then right at the end discovered that very conveniently there is now a built in option, which is ridiculously convenient! Check it: https://docs.travis-ci.com/user/deployment/pages/

**Comment by robhowell** [comment]
@F-Ruxton I've created a gh-pages branch, but I don't have access to the repo's settings to actually enable GitHub Pages - when you get a chance could you please do that? If you go to the Taskata repo Settings (the last tab), then under "GitHub Pages", select the gh-pages branch and then click on Save.

**Comment by F-Ruxton** [comment]
@robhowell Looks like you managed to save the gh-pages branch as the pages source in the end? Awesome that you can deploy just like that :) Just been to the site and it's actually the readme at the moment though haha. I'm sure we can fix that anyway. Do I still need to set up firebase eg for the database?

**Comment by robhowell** [comment]
Win! I didn't set it, but maybe when I created the gh-pages branch it did it by default, nice!

Yep, still need to setup Firebase etc 👍🏼

**Comment by F-Ruxton** [comment]
Ok cool, reading about that and travis this morning. Will get back to you. Not sure where I need to add you in on travis, seems like runs the tests on every pull request to the central repository. Just got to set up the .travis.yml and then it all happens automatically. Or am I missing something?

**Comment by F-Ruxton** [comment]
Nice, the basic travis.yml to run tests and deploy to gh-pages "should" be working :) Can you see that stuff happening at travis-ci.org or is that the bit I need to add you for?

**Comment by F-Ruxton** [comment]
![](https://travis-ci.org/F-Ruxton/taskata.svg?branch=master) :)

**Comment by F-Ruxton** [comment]
Will try to sort out firebase next

**Comment by robhowell** [comment]
@F-Ruxton Sorry forgot to say earlier, yep I have access to it in Travis - I just tried running the build manually to get it to redeploy to gh-pages (apparently it skips the deploy when it's a pull request) but gh-pages still isn't showing the CNAME in the root like I'd hoped it would. Will have to look into it further tonight.

**Comment by F-Ruxton** [comment]
Ok, sounds good. Interesting that it skips the deploy for pulls, something to update later on?
