### ISSUE TITLE
Decide on MVP version of UI/UX

### ISSUE THREAD

**Issue by robhowell** [F-Ruxton/taskata#6]

**Comment by F-Ruxton** [comment]
![web wireframe1 - landing page](https://cloud.githubusercontent.com/assets/22370438/25624027/27032fe8-2f50-11e7-942d-f9a4ffc5c5ec.jpg)

![to do page - to do page](https://cloud.githubusercontent.com/assets/22370438/25624032/2ae035fc-2f50-11e7-90cd-cf5b31d5f0a1.jpg)

**Comment by F-Ruxton** [comment]
Simplest app:
* user sign in using email and password
* create to-do list
* to-do list persisted on firebase
